Fix an error log if the platform doesn't support to decode audio file to PCM audio buffer. (#901)
The error log is :

TypeError: Cannot set property 'width' of null
| at audioBuffer.update (usr_main.js:2350:32)
| at eval (src/cocos-js/cc.js:44593:29)